version: "3"

services:
  
  swagger-ui:
    image: swaggerapi/swagger-ui:v3.0.5
    ports:
      - "8000:8080"

  employee-service:
    image: com.takeaway/take-away-employee-service:latest
    ports:
      - "8001:8001"
    links:
      - talent-management-db
 
  event-service:
    image: com.takeaway/take-away-event-service:latest
    ports:
      - "8002:8080"
    links:
      - timeseries-db

  message-broker:
    image: rabbitmq:3.7.7-management
    ports:
      - "5672:5672"      
      - "15672:15672"
    volumes:
      - ./message-broker/conf/rabbitmq.conf:/etc/rabbitmq.conf:ro
      - ./message-broker/conf/rabbitmq.definitions.json:/etc/rabbitmq/definitions.json:ro

  timeseries-db:
    image: influxdb:1.6.0
    ports:
      - "8086:8086"
    env_file:
      - './database/event/conf/env.influxdb'    
    volumes:
      - ./database/event/conf/influxdb.conf:/etc/influxdb/influxdb.conf:ro

  talent-management-db:
    image: mongo:4.0.0
    ports:
      - "27017:27017"
    volumes:
      - ./database/employee/data/credential.js:/docker-entrypoint-initdb.d/credential.js:ro     
    environment:
      MONGO_INITDB_DATABASE: talent-management
